# Generated by Django 2.2.2 on 2019-08-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190802_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
